// ============================================================
//  data.js  –  Nodos y aristas del grafo (25 departamentos)
//  Distancias aproximadas en KM por carretera entre capitales
//  vecinas (grafo no-dirigido).
// ============================================================

const DEPARTAMENTOS = {
  amazonas:   { nombre: "Amazonas",   capital: "Chachapoyas",  lat: -6.2318,  lng: -77.8711 },
  ancash:     { nombre: "Áncash",     capital: "Huaraz",       lat: -9.5269,  lng: -77.5278 },
  apurimac:   { nombre: "Apurímac",   capital: "Abancay",      lat: -13.6347, lng: -72.8816 },
  arequipa:   { nombre: "Arequipa",   capital: "Arequipa",     lat: -16.4090, lng: -71.5375 },
  ayacucho:   { nombre: "Ayacucho",   capital: "Ayacucho",     lat: -13.1588, lng: -74.2236 },
  cajamarca:  { nombre: "Cajamarca",  capital: "Cajamarca",    lat: -7.1638,  lng: -78.5008 },
  callao:     { nombre: "Callao",     capital: "Callao",       lat: -12.0565, lng: -77.1181 },
  cusco:      { nombre: "Cusco",      capital: "Cusco",        lat: -13.5170, lng: -71.9785 },
  huancavelica:{ nombre:"Huancavelica",capital:"Huancavelica", lat: -12.7870, lng: -74.9757 },
  huanuco:    { nombre: "Huánuco",    capital: "Huánuco",      lat: -9.9298,  lng: -76.2422 },
  ica:        { nombre: "Ica",        capital: "Ica",          lat: -14.0678, lng: -75.7286 },
  junin:      { nombre: "Junín",      capital: "Huancayo",     lat: -12.0651, lng: -75.2049 },
  lalibertad: { nombre: "La Libertad",capital: "Trujillo",     lat: -8.1119,  lng: -79.0289 },
  lambayeque: { nombre: "Lambayeque", capital: "Chiclayo",     lat: -6.7714,  lng: -79.8409 },
  lima:       { nombre: "Lima",       capital: "Lima",         lat: -12.0464, lng: -77.0428 },
  loreto:     { nombre: "Loreto",     capital: "Iquitos",      lat: -3.7491,  lng: -73.2538 },
  madrededios:{ nombre:"Madre de Dios",capital:"Puerto Maldonado",lat:-12.5933,lng:-69.1891},
  moquegua:   { nombre: "Moquegua",   capital: "Moquegua",     lat: -17.1928, lng: -70.9328 },
  pasco:      { nombre: "Pasco",      capital: "Cerro de Pasco",lat:-10.6855, lng: -76.2622 },
  piura:      { nombre: "Piura",      capital: "Piura",        lat: -5.1945,  lng: -80.6328 },
  puno:       { nombre: "Puno",       capital: "Puno",         lat: -15.8402, lng: -70.0219 },
  sanmartin:  { nombre: "San Martín", capital: "Moyobamba",    lat: -6.0340,  lng: -76.9720 },
  tacna:      { nombre: "Tacna",      capital: "Tacna",        lat: -18.0066, lng: -70.2480 },
  tumbes:     { nombre: "Tumbes",     capital: "Tumbes",       lat: -3.5667,  lng: -80.4515 },
  ucayali:    { nombre: "Ucayali",    capital: "Pucallpa",     lat: -8.3791,  lng: -74.5539 },
};

// Aristas del grafo: [origen, destino, distancia_km]
// Distancias aproximadas por carretera principal
const CONEXIONES = [
  ["tumbes",      "piura",        282],
  ["piura",       "lambayeque",   209],
  ["piura",       "cajamarca",    436],
  ["lambayeque",  "cajamarca",    260],
  ["lambayeque",  "lalibertad",   209],
  ["cajamarca",   "amazonas",     215],
  ["cajamarca",   "lalibertad",   295],
  ["cajamarca",   "sanmartin",    445],
  ["amazonas",    "sanmartin",    320],
  ["lalibertad",  "ancash",       192],
  ["lalibertad",  "sanmartin",    380],
  ["sanmartin",   "loreto",       870],
  ["sanmartin",   "huanuco",      430],
  ["ancash",      "lima",         408],
  ["ancash",      "huanuco",      295],
  ["huanuco",     "pasco",        130],
  ["huanuco",     "loreto",       830],
  ["huanuco",     "ucayali",      460],
  ["pasco",       "junin",        174],
  ["pasco",       "ucayali",      390],
  ["junin",       "lima",         298],
  ["junin",       "huancavelica", 148],
  ["junin",       "ayacucho",     351],
  ["junin",       "cusco",        628],
  ["lima",        "callao",        16],
  ["lima",        "ica",          305],
  ["lima",        "huancavelica", 445],
  ["ica",         "ayacucho",     318],
  ["ica",         "arequipa",     601],
  ["huancavelica","ayacucho",     235],
  ["ayacucho",    "apurimac",     194],
  ["ayacucho",    "cusco",        518],
  ["apurimac",    "cusco",        193],
  ["apurimac",    "arequipa",     542],
  ["cusco",       "puno",         388],
  ["cusco",       "madrededios",  560],
  ["cusco",       "arequipa",     521],
  ["arequipa",    "puno",         297],
  ["arequipa",    "moquegua",     214],
  ["moquegua",    "tacna",        159],
  ["moquegua",    "puno",         311],
  ["puno",        "madrededios",  483],
  ["ucayali",     "loreto",       835],
  ["ucayali",     "madrededios",  488],
  ["loreto",      "amazonas",     700],
];

export { DEPARTAMENTOS, CONEXIONES };